import 'package:flutter/material.dart';

Color primmarycolor = const Color(0xff007BFF);
Color lightblue = const Color(0xff78BBE6);
Color darkblue = const Color(0xffDDDDDD);
Color white = const Color(0xffFFFFFF);
Color offwhite = const Color(0xffDDDDDD);
Color lightgrey = const Color(0xffDDDDDD);
Color greytext = const Color(0xff787575);
Color darktext = const Color(0xff494747);
Color knokgrey = const Color(0xff1A1F36);
Color lightback = const Color(0xfff0f7ff);
Color pink = const Color(0xffFFA8AE);
Color black2 = const Color(0xff3f3f3f);
Color black = Colors.black;
Color greyText2 = const Color(0xff9fbdc4);
Color greyText3 = const Color(0xff15104d);
Color greyText4 = const Color(0xff2f4246);
Color greyColor = const Color(0xffbdd2d7);
Color lightGrey = const Color(0xFF709DA7);
Color blueColor = const Color(0xff007aff);
Color lightBlueColor = const Color(0xffb0d6ff);
Color bgColor = const Color(0xfff3f3f3);
Color redColor = const Color(0xffdc362e);
Color appBarBorderColor = const Color(0xffd3e1e4);
Color greenColor = const Color(0xff57b060);
Color yellowColor = const Color(0xffaf9f30);
