import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "CurrantWork": "Currant work ",
          "MyJobs": "My Jobs",
          "Services": "Services",
          "Education": "Education ",
          "Status": "Status ",
          "CustomersFeedback": "Customers Feedback",
          "Seeall": "See all",
          "Customer": "Customer",
          "anyOtherRequirement": "Any Other Requirement",
          "SelectServices": "Select Services",
          "SelectAvailability": "Select Availability",
          "AvailabilityFrom": "AvailabilityFrom",
          "MyRequest": "MyRequest",
          "Submit": "Submit",
          "SpecialRequirements": "Special requirements",
          "NA": "NA",
          "enterTotalAmount": "Enter total Amount",
          "yourBid": "Your Bid",
          "alljob": "Proposal",
          "proposal": "Received Proposal",
          "continue": "Continue",
          "Next": "Next",
          "very": "Verify",
          "ServicesNeeded": "Services Needed: ",
          "AvailabilityTime": "Availability Time: ",
          "CompanyName": "Company Name",
          "BidAmount": "Bid Amount: ",
          "sendcodeagain": "Resend code",
          "login": "Sign In",
          "verify": "Verify OTP",
          "sentcode": "We've sent a code to",
          "again": "Send code again",
          "youcango": "You can now go with",
          "spark": "Sparkle",
          "home": "Home",
          "notification": "Notification",
          "jobs": "My Jobs",
          "request": "Request",
          "allreque": "All Requests",
          "profile": "Profile",
          "firstname": "First Name",
          "familyname": "Family Name",

          "p1": "Home Cleaning Made Easy",
          "p2": "Flexible Booking Options",
          "p3": "Convenient Location Selection",
          "p1s": "Enjoy the convenience of scheduling a professional cleaner with just a few taps on your phone.",
          "p2s": "Our app lets you select a suitable date and time that fits seamlessly into your busy schedule.",
          "p3s":
              "Whether it's your home, office, or any other preferred place, our app allows you to effortlessly choose the exact location for the cleaning service.",
          "Notifications": "Notifications",
          "Availability": "Availability",
          "AvailabilityDate": "Availability Date",
          "AllJobs": "AllJobs",

          //New Ones
          "Sign In": "Sign In",
          "Phone Number": "Phone Number",
          "Remember me": "Remember me",
          "Please Enter mobile no.": "Please Enter mobile no.",
          "Invalid number": "Invalid number",
          'Please Enter 8 Length Phone Number': 'Please Enter 8 Length Phone Number',
          "Continue with Google": "Continue with Google",
          "You don't have an account ?": "You don't have an account ?",
          "Signup": "Sign up",
          'Create your account and enjoy our services': 'Create your account and enjoy our services',
          "Please Enter all value": "Please Enter all value",
          "Create my account": "Create my account",
          "privacyPolicyText": "By creating an account, you accept our Terms and conditions you read our Privacy Policy.",
          "4GigitMsg": "Please enter the 4-digit code send you to at",
          "Please Enter Otp": "Please Enter Otp",
          "Welcome To Sparkle": "Welcome To Sparkle",
          "Take a tour": "Take a tour",
          "Skip for now": "Skip for now",
          "Home Cleaning Made Easy": "Home Cleaning Made Easy",
          "Choose Time and Date": "Choose Time and Date",
          "Convenient Location": "Convenient Location",
          "desc1": "Get your home professionally cleaned with few taps",
          "desc2": "A calendar with different time slots highlighted",
          "desc3": "We offer our services in a variety of locations.",
          "Skip and access my account": "Skip and access my account",
          "Start My Tour": "Start My Tour",
          "Previous": "Previous",
          "Finish": "Finish",
          "My Profile": "My Profile",
          "Modify my Profile": "Modify my Profile",
          "Change language": "Change language",
          "About Sparkle": "About Sparkle",
          "Terms and condition": "Terms and condition",
          "Logout": "Logout",
          "Modify your profile": "Modify your profile",
          "Job": "Job",
          "Discard": "Discard",
          "Save changes": "Save changes",
          "Are you sure to logout from Sparkle ?": "Are you sure to logout from Sparkle ?", "Close": "Close",
          "Terms and conditions": "Terms and conditions",
          "Contact us": "Contact us",
          "Connect with us :": "Connect with us :",
          "Create a job": "Create a job",
          "Choose availability": "Choose availability",
          "Choose a date ": "Choose a date ",
          "Choose a time ": "Choose a time ",
          "Add a location": "Add a location",
          "Any Special requirements ?": "Any Special requirements ?",
          "Add any requirement for the services (Optional) ": "Add any requirement for the services (Optional) ", "Write here": "Write here",
          "Submit Job": "Submit Job",

          "Choose a service": "Choose a service",
          "Choose your location": "Choose your location",
          "Add the location": "Add the location",
          "Add a time": "Add a time",
          'Add a date': 'Add a date',
          'View Jobs': 'View Jobs',

          "Jobs in progress": "Jobs in progress",
          "Jobs done": "Jobs done",
          "No job has been created by you.": "No job has been created by you.",
          "You have": "You have",
          "proposals.": "proposals.",
          "Services for the job": "Services for the job",
          "View details": "View details",
          "Bid Amount  ": "Bid Amount  ",
          "Chat now": "Chat now",
          "Accept": "Accept",
          "Reject": "Reject",
          "Accepted": "Accepted",
          "Rejected": "Rejected",
          "Time": "Time",
          "Date": "Date",
          "Location": "Location",
          "New Proposals": "New Proposals",
          "View all": "View all",
          'Looking for another Proposal ?': 'Looking for another Proposal ?',
          "Create a new proposal": "Create a new proposal",
          'The Job posted successfully ': 'The Job posted successfully ',
          'Return to home page': 'Return to home page',
          "Home": "Home",
          "Notify": "Notify",
          "Jobs": "Jobs",
          "Add Job": "Add Job",
          "Edit my company profile": "Edit my company profile",
          "Company name": "Company name",
          "Company Description": "Company Description",
          "All": "All",
          "Unsubmitted": "Unsubmitted",
          "Under review": "Under review",
          "All jobs": "All jobs",
          'Sort by date': 'Sort by date',
          'Job services': 'Job services',
          "Start Bidding": "Start Bidding",
          "JOB ID": "JOB ID",
          "Job details": "Job details",
          "Amount": "Amount"
        },
        'ar_AR': {
          //New Ones:
          "Amount": "كمية",
          "Job details": "تفاصيل الوظيفة",
          "JOB ID": "معرف الوظيفة",
          "Start Bidding": "ابدأ المزايدة",
          'Job services': "خدمات العمل",
          'Sort by date': 'رتب حسب التاريخ',
          "All jobs": "جميع الوظائف",
          "Under review": "قيد المراجعة",
          "Unsubmitted": "لم يتم تقديمه",
          "All": "الجميع",
          "Company Description": "وصف الشركة",
          "Company name": "اسم الشركة",

          "Edit my company profile": "تحرير الملف التعريفي لشركتي",
          "Add Job": "أضف الوظيفة",
          "Jobs": "وظائف",
          "Notify": "يخطر",
          "Home": "بيت",
          'Return to home page': 'العوده للصفحة الرئيسية',
          'The Job posted successfully ': 'تم نشر الوظيفة بنجاح',
          "Create a new proposal": "إنشاء اقتراح جديد",
          'Looking for another Proposal ?': "هل تبحث عن اقتراح آخر؟",
          "View all": "عرض الكل",
          "Location": "موقع",
          "New Proposals": "مقترحات جديدة",
          "Date": "تاريخ",
          "Time": "وقت",
          "Rejected": "مرفوض",
          "Accepted": "قبلت",
          "Reject": "يرفض",
          "Accept": "يقبل",
          "Chat now": "الدردشة الآن",
          "Bid Amount  ": "قيمة المزايدة  ",
          "View details": "عرض التفاصيل",
          "Services for the job": "خدمات للوظيفة",
          "proposals.": "اقتراحات.",
          "You have": "لديك",
          "No job has been created by you.": "لم يتم إنشاء أي وظيفة بواسطتك.",
          "Jobs done": "تم إنجاز المهام",
          "Jobs in progress": "وظائف في التقدم",
          'View Jobs': "عرض الوظائف",
          'Add a date': "إضافة تاريخ",
          "Add a time": "أضف وقتا",
          "Add the location": "أضف الموقع",
          "Choose your location": "اختر موقعك",
          "Choose a service": "اختر خدمة",
          "Submit Job": "إرسال الوظيفة",
          "Write here": "اكتب هنا",
          "Add any requirement for the services (Optional) ": "إضافة أي متطلبات للخدمات (اختياري)",
          "Any Special requirements ?": "أي متطلبات خاصة؟",
          "Add a location": "أضف موقعًا",
          "Choose a time ": "اختر وقتًا ",
          "Choose a date ": "اختر تاريخا",
          "Choose availability": "اختر التوفر",
          "Create a job": "إنشاء وظيفة",
          "Connect with us :": "اتصل بنا :",
          "Contact us": "اتصل بنا",
          "Terms and conditions": "الأحكام والشروط",
          "Close": "يغلق",
          "Are you sure to logout from Sparkle ?": "هل أنت متأكد من تسجيل الخروج من سباركل؟",
          "Discard": "ينبذ",
          "Save changes": "حفظ التغييرات",
          "Job": "وظيفة",
          "Modify your profile": "تعديل ملف التعريف الخاص بك",
          "Logout": "تسجيل خروج",
          "Terms and condition": "الأحكام والشروط",
          "About Sparkle": "حول سباركل",
          "Change language": "تغيير اللغة",
          "Modify my Profile": "تعديل ملف التعريف الخاص بي",
          "My Profile": "ملفي",
          "Finish": "ينهي",
          "Previous": "سابق",
          "Start My Tour": "ابدأ جولتي",
          "Skip and access my account": "تخطي والوصول إلى حسابي",
          "desc1": "احصل على تنظيف منزلك بشكل احترافي بنقرات قليلة",
          "desc2": "تم تمييز التقويم بفترات زمنية مختلفة",
          "desc3": "نحن نقدم خدماتنا في مجموعة متنوعة من المواقع.",

          "Convenient Location": "موقع ملائم",
          "Choose Time and Date": "اختر الوقت والتاريخ",
          "Home Cleaning Made Easy": "تنظيف المنزل أصبح سهلاً",
          "Skip for now": "تخطي في الوقت الراهن",
          "Take a tour": "خذ جولة",
          "Welcome To Sparkle": "مرحبا بكم في البريق",
          "Please Enter Otp": "الرجاء إدخال كلمة المرور",
          "4GigitMsg": "الرجاء إدخال الرمز المكون من 4 أرقام الذي تم إرساله إليك على",
          "Sign In": "تسجيل الدخول",
          "Phone Number": "رقم التليفون",
          "Remember me": "تذكرنى",
          "Please Enter mobile no.": "الرجاء إدخال رقم الجوال",
          "MyRequest": "طلبي",
          "Invalid number": "رقم غير صالح",
          'Please Enter 8 Length Phone Number': "الرجاء إدخال رقم هاتف بطول 8",
          "Continue with Google": "تواصل مع جوجل",
          "You don't have an account ?": "ليس لديك حساب؟",
          "Signup": "اشتراك",
          'Create your account and enjoy our services': "أنشئ حسابك واستمتع بخدماتنا",
          "Please Enter all value": "الرجاء إدخال كافة القيمة",
          'Create my account': "إنشيء حسابي",
          "privacyPolicyText": "من خلال إنشاء حساب، فإنك توافق على الشروط والأحكام الخاصة بنا، وتقرأ سياسة الخصوصية الخاصة بنا.",

          "CurrantWork": "العمل الحالي",
          "Services": "الخدمات",
          "AvailabilityFrom": "وقت التوفر: ",
          "MyJobs": "وظائفي",
          "Education": "التعليم",
          "Status": "الحالة",
          "CustomersFeedback": "آراء العملاء",
          "Seeall": "عرض الكل",
          "Customer": "العميل",
          "anyOtherRequirement": "متطلب آخر",
          "SelectServices": "اختر الخدمات",
          "SelectAvailability": "اختر التوفر",
          "Submit": "إرسال",
          "SpecialRequirements": "متطلبات خاصة",
          "NA": "غير متوفر",
          "enterTotalAmount": "أدخل المبلغ الإجمالي",
          "yourBid": "عرضك",
          "alljob": "جميع الوظائف",
          "proposal": "ستلمت الاقتراح",
          "continue": "استمرار",
          "Next": "التالي",
          "very": "تحقق",
          "ServicesNeeded": "الخدمات المطلوبة: ",
          "AvailabilityTime": "وقت التوفر: ",
          "CompanyName": "اسم الشركة",
          "BidAmount": "مبلغ العرض: ",
          "sendcodeagain": "إرسال الرمز مجددا",
          "login": "تسجيل الدخول",
          "verify": "التحقق من OTP",
          "sentcode": "لقد قمنا بإرسال رمز إلى",
          "again": "تنظيف المنزل بسهولة",
          "youcango": "تنظيف المنزل بسهولة",
          "spark": "تنظيف المنزل بسهولة",
          "home": "تنظيف المنزل بسهولة",
          "notification": "تنظيف المنزل بسهولة",
          "jobs": "تنظيف المنزل بسهولة",
          "request": "تنظيف المنزل بسهولة",
          "allreque": "تنظيف المنزل بسهولة",
          "profile": "تنظيف المنزل بسهولة",
          "firstname": "تنظيف المنزل بسهولة",
          "familyname": "تنظيف المنزل بسهولة",

          "p1": "تنظيف المنزل بسهولة",
          "p2": "خيارات حجز مرنة",
          "p3": "فى كل مكان تريده",
          "p1s": "استمتع بسهولة تنظيف منزلك عن طريق خدمة مُنظِّف محترف بضغطة على هاتفك فقط.",
          "p2s": "يتيح لك تطبيقنا تحديد التاريخ والوقت المناسبين اللذين يتناسبان بسلاسة مع جدولك المزدحم.",
          "p3s": "سواء كان منزلك، مكتبك، أو أي مكان آخر تفضله، يتيح لك تطبيقنا اختيار الموقع المحدد لخدمة التنظيف بكل سهولة ويسر.",
          "Notifications": "إشعارات",
          "Availability": "التوفر",
          "Availability Date": "تاريخ التوفر",
          "AllJobs": "جميع الوظائف"
        },
      };
}
